### ISSUE TITLE
长时间播直播流 JNI ERROR

### ISSUE THREAD

**Issue by Drrino** [pili-engineering/PLDroidPlayer#1077]
01-22 17:15:25.089 12949-12997/com.grtech.sklive E/dalvikvm: JNI ERROR (app bug): local reference table overflow (max=512)
01-22 17:15:25.089 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 QCFuncLog L339 ----CHTTPIO2::Open leave! rc =        0. Used Time: 185
01-22 17:15:25.089 12949-12997/com.grtech.sklive W/dalvikvm: JNI local reference table (0xabeaadf0) dump:
      Last 10 entries (of 512):
01-22 17:15:25.089 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 CAdaptiveStreamHLS L989 segment size:586560
01-22 17:15:25.089 12949-12997/com.grtech.sklive W/dalvikvm:       511: 0x41b64528 java.lang.String "QPlayer"
          510: 0x41631cb8 java.lang.Class<android.util.Log>
          509: 0x41c1f080 java.lang.String "video/MP2T"
          508: 0x41c3e4f0 java.lang.String "application/vnd.... (29 chars)
          507: 0x41a74e78 java.lang.String "application/vnd.... (29 chars)
          506: 0x41a2cca8 java.lang.String "video/MP2T"
          505: 0x41a5bed0 java.lang.String "video/MP2T"
          504: 0x41c0eb28 java.lang.String "video/MP2T"
          503: 0x41a34c00 java.lang.String "video/MP2T"
          502: 0x41c1d610 java.lang.String "application/vnd.... (29 chars)
      Summary:
            1 of java.lang.Class
          510 of java.lang.String (510 unique instances)
            1 of byte[] (1036 elements)
01-22 17:15:25.089 12949-12997/com.grtech.sklive E/dalvikvm: Failed adding to JNI local ref table (has 512 entries)
01-22 17:15:25.089 12949-12997/com.grtech.sklive I/dalvikvm: "Thread-6314" prio=5 tid=28 RUNNABLE
      | group="main" sCount=0 dsCount=0 obj=0x41c5b618 self=0xab84c668
      | sysTid=12997 nice=0 sched=0/0 cgrp=apps handle=-1418911672
      | state=R schedstat=( 8858490330 5826631488 163306 ) utm=622 stm=263 core=2
        at android.util.Log.println_native(Native Method)
        at android.util.Log.i(Log.java:178)
        at com.pili.pldroid.player.common.a.a(Logger.java:35)
        at com.qiniu.qplayer.mediaEngine.MediaPlayer.postEventFromNative(MediaPlayer.java:1154)
        at dalvik.system.NativeStart.run(Native Method)
01-22 17:15:25.089 12949-12997/com.grtech.sklive E/dalvikvm: VM aborting
01-22 17:15:25.089 12949-12997/com.grtech.sklive A/libc: Fatal signal 6 (SIGABRT) at 0x00003295 (code=-6), thread 12997 (CMsgMng)
01-22 17:15:25.099 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 C_HLS_Entity L1085 event callback the root url:http://sk.live.otvcloud.com/otv/skcc/live/channel1/index.m3u8?k=5971b6026a43411856512f3c1a1c22b9&t=5C46DC87&UID=03c77a7eebf695339919be018bd5f32a
    Info TAB8A1BD0 C_HLS_Entity L1087 event callback the url:2300.m3u8?k=5971b6026a43411856512f3c1a1c22b9&t=5C46DC87&UID=03c77a7eebf695339919be018bd5f32a
    Info TAB8A1BD0 QCFuncLog L321 ----CHTTPIO2::Open Value is 00000000 start.
    Info TAB8A1BD0 QCFuncLog L321 --------CHTTPClient::Connect Value is 00000000 start.
    Info TAB8A1BD0 CHTTPClient L709 The connect IP is 61.147.235.120
    Info TAB8A1BD0 CHTTPClient L302 Parse DNS used time = 0
    Info TAB8A1BD0 QCFuncLog L321 ------------CHTTPClient::ConnectServer Value is 00002710 start.
01-22 17:15:25.109 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 QCFuncLog L339 ------------CHTTPClient::ConnectServer leave! rc =        0. Used Time: 14
01-22 17:15:25.129 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 QCFuncLog L339 --------CHTTPClient::Connect leave! rc =        0. Used Time: 29
    Info TAB8A1BD0 QCFuncLog L339 ----CHTTPIO2::Open leave! rc =        0. Used Time: 29
01-22 17:15:25.139 12949-13961/com.grtech.sklive I/@@@QCLOG: Info TAB8A1BD0 QCFuncLog L321 ----CHTTPIO2::Close Value is 00000000 start.
    Info TAB8A1BD0 QCFuncLog L343 ----CHTTPIO2::Close leave! no return. Ussed Time: 6
    Info TAB8A1BD0 C_HLS_Entity L226 NewURL:http://sk.live.otvcloud.com/otv/skcc/live/channel1/2300.m3u8?k=5971b6026a43411856512f3c1a1c22b9&t=5C46DC87&UID=03c77a7eebf695339919be018bd5f32a
    Info TAB8A1BD0 C_HLS_Entity L227 URL:2300.m3u8?k=5971b6026a43411856512f3c1a1c22b9&t=5C46DC87&UID=03c77a7eebf695339919be018bd5f32a
    Info TAB8A1BD0 C_M3U_Manager L443 PlayList ID:0, Min Seq:477738, Max Seq:477741, Dvr Duration:8000

**Comment by Drrino** [comment]
如果有人使用2.1.6版本遇到相同问题，可以使用options.setInteger(AVOptions.KEY_LOG_LEVEL, 5);
