### ISSUE TITLE
偶现的播放视频导致崩溃的问题

### ISSUE THREAD

**Issue by zengxk** [pili-engineering/PLDroidPlayer#1095]
java堆栈信息：

#00 pc 0021f68e /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
--
2 #01 pc 0021f6a3 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
3 #02 pc 0021f679 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
4 #03 pc 0021eef1 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
5 #04 pc 0021eb55 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
6 #05 pc 0021eb1b /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
7 #06 pc 0021f36b /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so (operator new(unsigned int)+70) [armeabi-v7a]
8 #07 pc 0021f3af /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so (operator new[](unsigned int)+4) [armeabi-v7a]
9 #08 pc 00040c25 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
10 #09 pc 0007ef03 /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
11 #10 pc 0008b32d /data/app/com.hhgk.tsang.smartadsystem-1/lib/arm/libQPlayer.so [armeabi-v7a]
12 #11 pc 00c360ed /data/app/com.hhgk.tsang.smartadsystem-1/oat/arm/base.odex (oatexec+3068141) [armeabi]
13 java:
14 com.qiniu.qplayer.mediaEngine.MediaPlayer.b(MediaPlayer.java:366)
15 com.pili.pldroid.player.PLMediaPlayer.prepareAsync(PLMediaPlayer.java:210)
16 com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:661)
17 com.pili.pldroid.player.widget.a.setVideoURI(PLBaseVideoView.java:345)
18 com.pili.pldroid.player.widget.PLVideoTextureView.setVideoURI(PLVideoTextureView.java:21)
19 com.pili.pldroid.player.widget.a.setVideoURI(PLBaseVideoView.java:328)
20 com.pili.pldroid.player.widget.PLVideoTextureView.setVideoURI(PLVideoTextureView.java:21)
21 com.pili.pldroid.player.widget.a.setVideoPath(PLBaseVideoView.java:302)
22 com.pili.pldroid.player.widget.PLVideoTextureView.setVideoPath(PLVideoTextureView.java:21)
23 com.hhgk.tsang.smartadsystem.MainActivityNew.playVideo(MainActivityNew.java:1810)
24 com.hhgk.tsang.smartadsystem.MainActivityNew.playNormalAdItem(MainActivityNew.java:1539)
25 com.hhgk.tsang.smartadsystem.MainActivityNew.startPlayNormalAd(MainActivityNew.java:1432)
26 com.hhgk.tsang.smartadsystem.MainActivityNew.access$400(MainActivityNew.java:117)
27 com.hhgk.tsang.smartadsystem.MainActivityNew$19.onCompletion(MainActivityNew.java:1032)

**Comment by zengxk** [comment]
日志信息：

701 3200 I QPlayer : postEventFromNative: 11020002, 1, 0
--
104-01 18:52:48.385 701 3200 I @@@QCLOG: Info T9D376930 QCFuncLog L344 ----COMBoxMng::DoSeek leave! rc = 0. Used Time: 20
204-01 18:52:48.386 701 3200 I QPlayer : postEventFromNative: 16000007, 0, 0
304-01 18:52:48.386 701 701 I QPlayer : stop + State: COMPLETED
404-01 18:52:48.386 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ----COMBoxMng::Stop Value is 00000002 start.
504-01 18:52:48.386 701 3200 I @@@QCLOG: QCMSG 3QC_MSG_SNKV_EOS 00 : 00 : 10 : 403 0 0
604-01 18:52:48.396 701 701 I @@@QCLOG: Info TB6F84B34 CBoxVideoRnd L212 Video Render num: 0 - 0
704-01 18:52:48.398 701 5123 I @@@QCLOG: Info T9E835930 CNDKAudioRnd L83 OnStop!
804-01 18:52:48.401 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L344 ----COMBoxMng::Stop leave! rc = 0. Used Time: 15
904-01 18:52:48.401 701 701 I QPlayer : stop -
1004-01 18:52:48.402 701 701 I MainActivityNew:
1104-01 18:52:48.402 701 701 I MainActivityNew: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1204-01 18:52:48.402 701 701 I MainActivityNew: │ main, com.hhgk.tsang.smartadsystem.MainActivityNew.startPlayNormalAd(MainActivityNew.java:1427)
1304-01 18:52:48.402 701 701 I MainActivityNew: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
1404-01 18:52:48.402 701 701 I MainActivityNew: │ startPlayNormalAd--showCloseAd = false
1504-01 18:52:48.402 701 701 I MainActivityNew: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1604-01 18:52:48.402 701 701 I QPlayer : setLooping false
1704-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ----COMBoxMng::SetParam Value is 11000340 start.
1804-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L344 ----COMBoxMng::SetParam leave! rc = 0. Used Time: 0
1904-01 18:52:48.402 701 701 I QPlayer : setDataSource: /storage/emulated/0/tkface/NormalAds/c17c138ddf684a4f98a6f239308efc4f.MP4 State: COMPLETED
2004-01 18:52:48.402 701 701 I QPlayer : setSurface + State: COMPLETED
2104-01 18:52:48.402 701 701 I QPlayer : setSurface -
2204-01 18:52:48.402 701 701 I QPlayer : prepareAsync State: COMPLETED
2304-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 jniPlayer L130 Open source: /storage/emulated/0/tkface/NormalAds/c17c138ddf684a4f98a6f239308efc4f.MP4
2404-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ----COMBoxMng::Open Value is 00000000 start.
2504-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 --------COMBoxMng::Close Value is 00000000 start.
2604-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------COMBoxMng::Stop Value is 00000004 start.
2704-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L344 ------------COMBoxMng::Stop leave! rc = 0. Used Time: 0
2804-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------CBoxVideoRnd::~CBoxVideoRnd Value is 00000000 start.
2904-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ------------CBoxVideoRnd::~CBoxVideoRnd leave! no return. Ussed Time: 0
3004-01 18:52:48.402 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------CBoxVideoDec::~CBoxVideoDec Value is 00000000 start.
3104-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ------------CBoxVideoDec::~CBoxVideoDec leave! no return. Ussed Time: 7
3204-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------CBoxAudioRnd::~CBoxAudioRnd Value is 00000000 start.
3304-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ------------CBoxAudioRnd::~CBoxAudioRnd leave! no return. Ussed Time: 0
3404-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------CBoxAudioDec::~CBoxAudioDec Value is 00000000 start.
3504-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ------------CBoxAudioDec::~CBoxAudioDec leave! no return. Ussed Time: 0
3604-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ------------CBoxSource::Close Value is 00000000 start.
3704-01 18:52:48.409 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ----------------CQCSource::Close Value is 00000000 start.
3804-01 18:52:48.409 701 3200 I QPlayer : postEventFromNative: 1600000e, 0, 0
3904-01 18:52:48.409 701 3200 I @@@QCLOG: QCMSG QC_MSG_PLAY_STOP 00 : 00 : 00 : -01 0 10048
4004-01 18:52:48.411 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ----------------CQCSource::Close leave! no return. Ussed Time: 2
4104-01 18:52:48.411 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L326 ----------------CQCSource::Close Value is 00000000 start.
4204-01 18:52:48.411 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ----------------CQCSource::Close leave! no return. Ussed Time: 0
4304-01 18:52:48.411 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L348 ------------CBoxSource::Close leave! no return. Ussed Time: 2
4404-01 18:52:48.411 701 701 I @@@QCLOG: Info TB6F84B34 QCFuncLog L344 ----COMBoxMng::Close leave! rc = 0. Used Time: 9
4504-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 COMBoxMng L1796 The Event ID = 70000001
4604-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ----COMBoxMng::OnHandleEvent Value is 70000001 start.
4704-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------COMBoxMng::DoOpen Value is 00000000 start.
4804-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ------------CBoxSource::OpenSource Value is 00000000 start.
4904-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ----------------CBoxSource::Close Value is 00000000 start.
5004-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 ----------------CBoxSource::Close leave! no return. Ussed Time: 0
5104-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ----------------CBoxSource::GetCache Value is 00000000 start.
5204-01 18:52:48.412 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 ----------------CBoxSource::GetCache leave! no return. Ussed Time: 0
5304-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ----------------CMP4ParserBase::ReadBoxMoov Value is 00000000 start.
5404-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L62 MOOVDebug box: moov 36 4913
5504-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: mvhd 36 108 UsedTime: Box = 0 Moov = 0 2281017
5604-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: trak 152 1958 UsedTime: Box = 0 Moov = 0 2281017
5704-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: tkhd 152 92 UsedTime: Box = 0 Moov = 0 2281017
5804-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: mdia 252 1822 UsedTime: Box = 0 Moov = 0 2281017
5904-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: mdhd 252 32 UsedTime: Box = 0 Moov = 0 2281017
6004-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: hdlr 284 68 UsedTime: Box = 0 Moov = 0 2281017
6104-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: minf 360 1714 UsedTime: Box = 0 Moov = 0 2281017
6204-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: vmhd 360 20 UsedTime: Box = 0 Moov = 0 2281017
6304-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: dinf 380 36 UsedTime: Box = 0 Moov = 0 2281017
6404-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: stbl 424 1650 UsedTime: Box = 0 Moov = 0 2281017
6504-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsd 424 202 UsedTime: Box = 0 Moov = 0 2281017
6604-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStts Value is 00000000 start.
6704-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 --------------------CMP4ParserBase::ReadBoxStts leave! no return. Ussed Time: 0
6804-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stts 626 24 UsedTime: Box = 0 Moov = 0 2281017
6904-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStsc Value is 00000000 start.
7004-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L969 Read entry = 1, total 1, downpos = 2281017 678 2281017
7104-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStsc leave! rc = 1. Used Time: 0
7204-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsc 650 28 UsedTime: Box = 0 Moov = 0 2281017
7304-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStsz Value is 00000000 start.
7404-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L1088 Read entry = 300, total 300, downpos = 2281017 1898 2281017
7504-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStsz leave! rc = 300. Used Time: 0
7604-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsz 678 1220 UsedTime: Box = 0 Moov = 0 2281017
7704-01 18:52:48.414 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStco Value is 00000000 start.
7804-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L862 Read entry = 30, total 30, downpos = 2281017 2034 2281017
7904-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStco leave! rc = 30. Used Time: 0
8004-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stco 1898 136 UsedTime: Box = 0 Moov = 0 2281017
8104-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStss Value is 00000000 start.
8204-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 --------------------CMP4ParserBase::ReadBoxStss leave! no return. Ussed Time: 0
8304-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stss 2034 32 UsedTime: Box = 0 Moov = 1 2281017
8404-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: edts 2066 36 UsedTime: Box = 0 Moov = 1 2281017
8504-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: iods 2102 27 UsedTime: Box = 0 Moov = 1 2281017
8604-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::BuildSampleTab Value is 00000000 start.
8704-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 --------------------CMP4ParserBase::BuildSampleTab leave! no return. Ussed Time: 0
8804-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: trak 2137 2756 UsedTime: Box = 0 Moov = 1 2281017
8904-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: tkhd 2137 92 UsedTime: Box = 0 Moov = 1 2281017
9004-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: mdia 2237 2620 UsedTime: Box = 0 Moov = 1 2281017
9104-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: mdhd 2237 32 UsedTime: Box = 0 Moov = 1 2281017
9204-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: hdlr 2269 68 UsedTime: Box = 0 Moov = 1 2281017
9304-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: minf 2345 2512 UsedTime: Box = 0 Moov = 1 2281017
9404-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: smhd 2345 16 UsedTime: Box = 0 Moov = 1 2281017
9504-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: dinf 2361 36 UsedTime: Box = 0 Moov = 1 2281017
9604-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L418 MOOVDebug box: stbl 2405 2452 UsedTime: Box = 0 Moov = 1 2281017
9704-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsd 2405 100 UsedTime: Box = 0 Moov = 1 2281017
9804-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStts Value is 00000000 start.
9904-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 --------------------CMP4ParserBase::ReadBoxStts leave! no return. Ussed Time: 0
10004-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stts 2505 24 UsedTime: Box = 0 Moov = 1 2281017
10104-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStsc Value is 00000000 start.
10204-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L969 Read entry = 22, total 22, downpos = 2281017 2809 2281017
10304-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStsc leave! rc = 22. Used Time: 0
10404-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsc 2529 280 UsedTime: Box = 0 Moov = 1 2281017
10504-01 18:52:48.415 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStsz Value is 00000000 start.
10604-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L1088 Read entry = 471, total 471, downpos = 2281017 4713 2281017
10704-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStsz leave! rc = 471. Used Time: 1
10804-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stsz 2809 1904 UsedTime: Box = 1 Moov = 2 2281017
10904-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::ReadBoxStco Value is 00000000 start.
11004-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L862 Read entry = 30, total 30, downpos = 2281017 4849 2281017
11104-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------------------CMP4ParserBase::ReadBoxStco leave! rc = 30. Used Time: 0
11204-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: stco 4713 136 UsedTime: Box = 0 Moov = 2 2281017
11304-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: edts 4849 36 UsedTime: Box = 0 Moov = 2 2281017
11404-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CMP4Parser L414 MOOVDebug box: udta 4885 64 UsedTime: Box = 0 Moov = 2 2281017
11504-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 --------------------CMP4ParserBase::BuildSampleTab Value is 00000000 start.
11604-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 --------------------CMP4ParserBase::BuildSampleTab leave! no return. Ussed Time: 0
11704-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L348 ----------------CMP4ParserBase::ReadBoxMoov leave! no return. Ussed Time: 2
11804-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 CQCSource L144 Min buf time 500, max buf time 10000
11904-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 ------------CBoxSource::OpenSource leave! rc = 0. Used Time: 4
12004-01 18:52:48.416 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ------------CBoxVideoDec::SetSource Value is 00000000 start.
12104-01 18:52:48.419 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 ------------CBoxVideoDec::SetSource leave! rc = 0. Used Time: 3
12204-01 18:52:48.419 701 3199 I @@@QCLOG: Info T9E922930 CNDKVideoRnd L147 Init WXH 1920 1080, 0xb8d40590
12304-01 18:52:48.419 701 3199 I @@@QCLOG: Info T9E922930 CNDKVideoRnd L291 Update Video Size: 1920 X 1080 Ratio: 1920 : 1080
12404-01 18:52:48.419 701 3199 I QPlayer : postEventFromNative: 15200003, 1920, 1080
12504-01 18:52:48.420 701 3199 I QPlayer : onVideoSizeChanged
12604-01 18:52:48.420 701 3199 I @@@QCLOG: Info T9E922930 CNDKVideoRnd L134 Set event done 1
12704-01 18:52:48.420 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L383 Event had handled! m_bEventDone = 1
12804-01 18:52:48.420 701 3199 I @@@QCLOG: Info T9E922930 CNDKVideoRnd L310 The m_bEventDone is 1
12904-01 18:52:48.420 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L326 ------------CBoxAudioDec::SetSource Value is 00000000 start.
13004-01 18:52:48.421 701 3200 I QPlayer : postEventFromNative: 1600000a, 0, 0
13104-01 18:52:48.421 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 ------------CBoxAudioDec::SetSource leave! rc = 0. Used Time: 1
13204-01 18:52:48.421 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 --------COMBoxMng::DoOpen leave! rc = 0. Used Time: 9
13304-01 18:52:48.421 701 3200 I @@@QCLOG: QCMSG QC_MSG_PLAY_OPEN_START 00 : 00 : 00 : 010 0 0
13404-01 18:52:48.422 701 3200 I QPlayer : postEventFromNative: 11000062, 2281017, 0
13504-01 18:52:48.423 701 3200 I @@@QCLOG: QCMSG QC_MSG_HTTP_CONTENT_SIZE 00 : 00 : 00 : 014 0 2281017
13604-01 18:52:48.423 701 3199 I QPlayer : postEventFromNative: 16000001, 0, 0
13704-01 18:52:48.425 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L609 Network QOS Type is -
13804-01 18:52:48.425 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L621 Network QOS ISP Name is -
13904-01 18:52:48.425 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L633 Network QOS Wifi Name is -
14004-01 18:52:48.425 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L640 Network QOS Signal DB is 0
14104-01 18:52:48.425 701 3199 I @@@QCLOG: Info T9E922930 CNDKPlayer L646 Network QOS Signal Level is 0
14204-01 18:52:48.425 701 3199 I QPlayer : network info: , , null, 0, 0
14304-01 18:52:48.425 701 3199 I QPlayer : onPrepared: 23 ms
14404-01 18:52:48.426 701 3199 I @@@QCLOG: Info T9E922930 COMBoxMng L1850 Open /storage/emulated/0/tkface/NormalAds/c17c138ddf684a4f98a6f239308efc4f.MP4 result = 0X00000000
14504-01 18:52:48.426 701 3199 I @@@QCLOG: Info T9E922930 QCFuncLog L344 ----COMBoxMng::OnHandleEvent leave! rc = 0. Used Time: 14
14604-01 18:52:48.427 701 3200 I QPlayer : postEventFromNative: 12000001, 1, 0
14704-01 18:52:48.427 701 3200 I @@@QCLOG: QCMSG QC_MSG_PARSER_NEW_STREAM 00 : 00 : 00 : 014 1 0
14804-01 18:52:48.428 701 3200 I QPlayer : postEventFromNative: 16000009, 0, 0
14904-01 18:52:48.428 701 3200 I @@@QCLOG: QCMSG QC_MSG_PLAY_DURATION 00 : 00 : 00 : 019 0 10048

**Comment by cq-zhou** [comment]
我也遇到这个问题了，你解决了么？

04-10 16:24:54.028 630 1967 E CrashHandler: UncaughtException detected: java.lang.NullPointerException: Attempt to read from field 'java.lang.Runnable com.qiniu.qplayer.mediaEngine.MediaPlayer$b.b' on a null object reference
--
13904-10 16:24:54.028 630 1967 E CrashHandler: at com.qiniu.qplayer.mediaEngine.MediaPlayer$b.c(MediaPlayer.java:1665)
14004-10 16:24:54.028 630 1967 E CrashHandler: at com.qiniu.qplayer.mediaEngine.MediaPlayer.d(MediaPlayer.java:1496)
14104-10 16:24:54.028 630 1967 E CrashHandler: at com.qiniu.qplayer.mediaEngine.MediaPlayer.B(MediaPlayer.java:1525)
14204-10 16:24:54.028 630 1967 E CrashHandler: at com.qiniu.qplayer.mediaEngine.MediaPlayer.postEventFromNative(MediaPlayer.java:1176)
