### ISSUE TITLE
弱网环境，视频缓冲时，调用stopPlayback会导致anr

### ISSUE THREAD

**Issue by tofaluanle** [pili-engineering/PLDroidPlayer#1164]
[traces.txt](https://github.com/pili-engineering/PLDroidPlayer/files/3868327/traces.txt)
at com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeStop(Native Method)
		at com.qiniu.qplayer.mediaEngine.MediaPlayer.e(MediaPlayer.java:473)
		at com.pili.pldroid.player.PLMediaPlayer.stop(PLMediaPlayer.java:267)
		at com.pili.pldroid.player.widget.a.b(PLBaseVideoView.java:686)
		at com.pili.pldroid.player.widget.a.stopPlayback(PLBaseVideoView.java:273)
		at com.pili.pldroid.player.widget.PLVideoTextureView.stopPlayback(PLVideoTextureView.java:21)
		at com.ziroom.player.ZrVideoView.stopPlayback(ZrVideoView.java:286)
		at com.ziroom.find.detail.luxury.LuxuryHouseDetailFragment.onDestroy(LuxuryHouseDetailFragment.java:2682)
		at android.support.v4.app.Fragment.performDestroy(Fragment.java:2699)
		at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1591)
		at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
		at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
		at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
		at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
		at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:274)
		at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
		at com.ziroom.commonlibrary.widget.base.BaseActivity.onDestroy(BaseActivity.java:539)
		at com.ziroom.find.detail.RentHouseDetailActivity.onDestroy(RentHouseDetailActivity.java:385)
		at android.app.Activity.performDestroy(Activity.java:7737)
		at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1327)
		at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
		at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5195)
		at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
		at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
		at android.os.Handler.dispatchMessage(Handler.java:112)
		at android.os.Looper.loop(Looper.java:216)
		at android.app.ActivityThread.main(ActivityThread.java:7625)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by lijun952048910** [comment]
我也遇到了，你这边解决了吗？

**Comment by tofaluanle** [comment]
找官网打电话或者提工单，跟他们单独要个2.1.5 兼容Q的包吧
