### ISSUE TITLE
com.pili.pldroid.player.network.onReceive(DNSCacheManager.java:153)

### ISSUE THREAD

**Issue by 751811032** [pili-engineering/PLDroidPlayer#215]
用户域名解析的，很多机型都会报这个错误。经常发生
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.pili.pldroid.player.network.a$1@42a959f0
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:781)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5217)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.pili.pldroid.player.network.a$1.onReceive(DNSCacheManager.java:153)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:764)
    ... 9 more

**Comment by Jhuster** [comment]
@751811032 嗯，谢谢反馈，这里确实有可能出现null指针，下一版会修复。

**Comment by Jhuster** [comment]
@751811032 能否列一下出现过问题的机型，我们这边测试复现一下。

**Comment by 751811032** [comment]
不好意思，不知道这个则呢么上传图片，放在下面这个链接里面
https://od.lk/f/MjRfNjU0NDIwXw       https://od.lk/f/MjRfNjU0NDE5Xw
我现在有没有从我的代码中解决的办法吗。注释掉那句DNS解析的代码是否可以避免这个问题
