### ISSUE TITLE
这个错，是什么原因导致的。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#226]
![Uploading 4.png…]()
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference

07-25 18:44:47.162: E/AndroidRuntime(20431): 	at android.view.ViewGroup.measureChild(ViewGroup.java:5500)
07-25 18:44:47.162: E/AndroidRuntime(20431): 	at com.pili.pldroid.player.widget.PLVideoTextureView.onMeasure(PLVideoTextureView.java:111)

07-25 18:44:47.162: E/AndroidRuntime(20431): 	at android.view.View.measure(View.java:17562)

**Comment by talentsxh** [comment]
升级就没事了
