### ISSUE TITLE
error sdk 23

### ISSUE THREAD

**Issue by bogdanovkp** [pili-engineering/PLDroidPlayer#311]
On application startup error

`     E/AndroidRuntime: FATAL EXCEPTION: main Process: PID: 4775
     java.lang.UnsatisfiedLinkError: dlopen failed:/lib/x86/libpldroidplayer.so: has text relocations
      at java.lang.Runtime.loadLibrary(Runtime.java:372) at java.lang.System.loadLibrary(System.java:1076)
                                                                              at com.pili.pldroid.player.SharedLibraryNameHelper.a(SharedLibraryNameHelper.java:57)
                                                                              at com.pili.pldroid.player.widget.VideoView$1.loadLibrary(VideoView.java:290)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:181)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:228)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:224)
                                                                              at com.pili.pldroid.player.widget.VideoView.openVideo(VideoView.java:284)
                                                                              at com.pili.pldroid.player.widget.VideoView.access$2800(VideoView.java:43)
                                                                              at com.pili.pldroid.player.widget.VideoView$9.surfaceCreated(VideoView.java:623)
                                                                              at android.view.SurfaceView.updateWindow(SurfaceView.java:582)
                                                                              at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
                                                                              at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by Jhuster** [comment]
@bogdanovkp  参考 `http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations`
```
    compileSdkVersion 22
    buildToolsVersion '22.0.1'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 22
    }
```

**Comment by bogdanovkp** [comment]
sdk 23 will not work?
