### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by skibug** [pili-engineering/PLDroidPlayer#358]
如果拉流地址出现连接被服务器拒绝，就会crash

日志如下：
E/IJKMEDIA: 拉流地址: Connection refused
11-17 14:29:39.014 6692-8521/com.yaowang.bluesharktv E/pldroid-player-native: failed to open input : 64 ms !
11-17 14:29:39.020 6692-6692/com.yaowang.bluesharktv E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-111)
11-17 14:29:39.020 6692-6692/com.yaowang.bluesharktv E/PLMediaPlayer: Error happened, what = -10000, extra = -111
11-17 14:29:39.141 6692-8517/com.yaowang.bluesharktv E/ErrorHandler: Thread(Thread[QosBroadcastManager,5,main]) got an uncaught exception: 
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage(int, java.lang.Object)' on a null object reference
                                                                         at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:135)
                                                                         at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:150)
                                                                         at com.qiniu.pili.droid.report.core.c.e(QosStatusRecorder.java:215)
                                                                         at com.qiniu.pili.droid.report.core.c.w(QosStatusRecorder.java:211)
                                                                         at com.qiniu.pili.droid.report.core.c.f(QosStatusRecorder.java:83)
                                                                         at com.qiniu.pili.droid.report.core.QosReceiver.a(QosReceiver.java:108)
                                                                         at com.qiniu.pili.droid.report.core.QosReceiver.a(QosReceiver.java:11)
                                                                         at com.qiniu.pili.droid.report.core.QosReceiver$1.onReceive(QosReceiver.java:52)
                                                                         at com.qiniu.pili.droid.report.QosBroadcastManager.b(QosBroadcastManager.java:300)

**Comment by skibug** [comment]
刚更新了1.40版本， 这个问题没有了
