### ISSUE TITLE
打个log也能出错吗

### ISSUE THREAD

**Issue by mengzhidaren** [pili-engineering/PLDroidPlayer#364]
java.lang.NullPointerException: println needs a message
                                                                 at android.util.Log.println_native(Native Method)
                                                                 at android.util.Log.d(Log.java:155)
                                                                 at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:308)
                                                                 at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:171)
                                                                 at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:218)
                                                                 at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:22)
                                                                 at com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage(QosReporter.java:79)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:177)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jhuster** [comment]
@mengzhidaren 请把 compile 'com.qiniu.pili:pili-android-qos:+ 升级到 13，即：
compile 'com.qiniu.pili:pili-android-qos:0.8.13
