### ISSUE TITLE
请问这个错误如解决，经常播放的时候，就会闪退

### ISSUE THREAD

**Issue by huxugang** [pili-engineering/PLDroidPlayer#391]
time: FATAL EXCEPTION: QosReporter
                                                                   
 java.lang.NullPointerException: println needs a message
 at android.util.Log.println_native(Native Method)
  at android.util.Log.d(Log.java:139)
  at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:308)
  at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:171)
 at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:218)
  at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:22)
 at com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage(QosReporter.java:79)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jhuster** [comment]
请升级到 `compile 'com.qiniu.pili:pili-android-qos:0.8.16`

**Comment by huxugang** [comment]
谢谢，我试试看
