### ISSUE TITLE
和其他的.so文件冲突

### ISSUE THREAD

**Issue by coderxu2016** [pili-engineering/PLDroidPlayer#414]
项目之前有.so文件，然后接入我们七牛的之后就无法拉流了。
这是错误日志：
ava.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:960)
                                                                     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:194)
                                                                     at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:177)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by Jhuster** [comment]
不太明白，我们的 jar 包和 so 是否都拷贝到项目中去了

**Comment by coderxu2016** [comment]
都拷进去了，如果把其他的.so文件去掉可以播放rtmp的流，但是一加上其他的.so就不行。

**Comment by Jhuster** [comment]
代码里还有 ijk 的 jar 和 so 吗？

**Comment by coderxu2016** [comment]
没有的，我也试过把其他的.so文件放到你们提供的demo下，也出现这种错误。

**Comment by Jhuster** [comment]
这个问题比较奇怪，其他的 so 是什么 so，你确定是因为把其他 so 拷贝到目录下就出问题？ 各个架构的文件夹下都拷贝了一份？

**Comment by coderxu2016** [comment]
对的，有极光的.so，阿里的.so。
