### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(int, long)

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#415]
友盟日志上面,发现这个错误,一般出现在OPPO  和VIVO 机型上,其他机型暂时没发现大问题,不知道是我这边客户端处理造成的还是So包的问题.

@Jhuster  求助.

**Comment by Vander-liu** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for long tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(int, long) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong__IJ)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.getPktTotalSize(IjkMediaPlayer.java:808)
	at com.pili.pldroid.player.PLMediaPlayer.stop(PLMediaPlayer.java:515)
	at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:549)
	at com.pili.pldroid.player.widget.a.c(PLBaseVideoView.java:481)
	at com.pili.pldroid.player.widget.a.setVideoURI(PLBaseVideoView.java:335)
	at com.pili.pldroid.player.widget.PLVideoTextureView.setVideoURI(PLVideoTextureView.java:20)
	at com.pili.pldroid.player.widget.a.setVideoPath(PLBaseVideoView.java:320)
	at com.pili.pldroid.player.widget.PLVideoTextureView.setVideoPath(PLVideoTextureView.java:20)
	at com.xiusekecai.ui.activity.LiveActivity$2.handleMessage(LiveActivity.java:268)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5714)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Vander-liu** [comment]
完成的日志忘发了.Sorry

**Comment by Vander-liu** [comment]
@Jhuster  求助.

**Comment by tanhx2008** [comment]
能给下完整 log 吗？
SDK 的版本号以及具体机型信息最好也给下，
另外，用我们的 Demo 是否会有同样问题？

**Comment by tanhx2008** [comment]
看上面的日志，应该是 jar 包和 so 不匹配，用我们最新的版本试一下呢

**Comment by Vander-liu** [comment]
这是我们App正式版 存在的问题, 上面是友盟的错误统计,
使用SDK 是 1.4.0

**Comment by Vander-liu** [comment]
![qq 20161230162341](https://cloud.githubusercontent.com/assets/16666953/21561781/6f69fcd0-ceac-11e6-8a7a-c2729d012fdf.png)

**Comment by Vander-liu** [comment]
jar包和So 不匹配....我去问问我们后台哈 ,有可能是这个问题 因为我们So  是打开App下载的.

**Comment by Vander-liu** [comment]
那 也就是说  每个版本的So和Jar包是一一对应的么,也就是意味着1.2.7版本的jar  是不能和1.4.0so一起用是吧 .

**Comment by Vander-liu** [comment]
@tanhx2008   我好像明白了什么..我去查查  谢谢您 /

**Comment by Vander-liu** [comment]
而且 播放也可以正常运转./

**Comment by Vander-liu** [comment]
基本可以排除 So文件和jar包不匹配的原因.上述 展示的图的渠道   是直接将So文件打入安装包的我刚刚检查了一下 也不存在问题.在这个三个渠道  其他的手机貌似可以正常运行 然而 大多数的 OPPO和VIVO 出现问题./

**Comment by Vander-liu** [comment]
@Jhuster   这个问题.  比较棘手 我这边 那天检查了jar包和So文件  版本 都没问题 .而且 我测试了几款 现有的手机 是没问题的./

**Comment by Jhuster** [comment]
@Vander-liu 你们使用的 SDK 版本号是多少

**Comment by Vander-liu** [comment]
MIN_SDK_VERSION = 16
TARGET_SDK_VERSION = 22

**Comment by Vander-liu** [comment]
使用的版本 是1.4.0
