### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#418]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:130)
	at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:144)
	at com.qiniu.pili.droid.report.core.c.e(QosStatusRecorder.java:217)
	at com.qiniu.pili.droid.report.core.c.w(QosStatusRecorder.java:206)
	at com.qiniu.pili.droid.report.core.c.o(QosStatusRecorder.java:131)
	at com.qiniu.pili.droid.report.core.QosReceiver$2$1.run(QosReceiver.java:69)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Vander-liu** [comment]
OPPO R7sPlus    Android版本 5.1.1

**Comment by Jhuster** [comment]
gradle 配置改为：`compile 'com.qiniu.pili:pili-android-qos:0.8.17`

**Comment by Vander-liu** [comment]
我们的播放器版本不升级 直接更改Gradle  版本 没问题么 .

**Comment by Vander-liu** [comment]
@Jhuster

**Comment by Jhuster** [comment]
@Vander-liu 嗯，可以的，没有问题。

**Comment by Vander-liu** [comment]
@Jhuster  #415问题也是我的.但是我感觉这个问题 比较棘手能劳烦 帮忙分析一下么 .

**Comment by Jhuster** [comment]
@Vander-liu 这个问题是我们依赖的qos sdk老版本在某些使用场景下处理不当导致的 null 指针问题，升级 qos sdk后应该可以修复的。

**Comment by Vander-liu** [comment]
恩恩.
