### ISSUE TITLE
1.5.0版本，在切换网络时有的手机会出现telephony模块的类转换问题

### ISSUE THREAD

**Issue by starryfang** [pili-engineering/PLDroidPlayer#489]
java.lang.ClassCastException: android.telephony.CellInfoLte cannot be cast to android.telephony.CellInfoGsm
	at com.pili.pldroid.player.report.common.a.i(Util.java:810)
	at com.pili.pldroid.player.report.core.f.i(QosStatusRecorder.java:89)
	at com.pili.pldroid.player.report.core.f.j(QosStatusRecorder.java:111)
	at com.pili.pldroid.player.report.core.f.d(QosStatusRecorder.java:67)
	at com.pili.pldroid.player.report.core.d$2$1.run(QosReceiver.java:52)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

java.lang.ClassCastException: android.telephony.CellInfoCdma cannot be cast to android.telephony.CellInfoLte
	at com.pili.pldroid.player.report.common.a.i(Util.java:814)
	at com.pili.pldroid.player.report.core.f.i(QosStatusRecorder.java:89)
	at com.pili.pldroid.player.report.core.f.j(QosStatusRecorder.java:111)
	at com.pili.pldroid.player.report.core.f.d(QosStatusRecorder.java:67)
	at com.pili.pldroid.player.report.core.d$2$1.run(QosReceiver.java:52)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Jhuster** [comment]
@starryfang 嗯，在部分双卡双待的手机上的确发现这个问题，抱歉，马上更新一个修复版本

**Comment by zhanchiFly** [comment]
电信4G上运行遇到同样的问题。

**Comment by Jhuster** [comment]
@zhanchiFly 升级到 1.5.1 版本，该问题已修复

**Comment by starryfang** [comment]
1.5.1 版本已修复此问题，感谢~
