### ISSUE TITLE
请问下这个错误如何解决

### ISSUE THREAD

**Issue by huxugang** [pili-engineering/PLDroidPlayer#512]
/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1330794744)
03-30 16:51:19.020 4168-4168/? E/PLMediaPlayer: Error happened, what = -10000, extra = -1330794744
03-30 16:51:19.020 4168-4168/? E/errorCodeerrorCode: -1330794744=====
03-30 16:51:19.020 4168-4168/? E/FRAME_TIMEOUT: false===
03-30 16:51:19.440 4168-14405/? E/AndroidRuntime: FATAL EXCEPTION: QosReporter
                                                  Process: com.dailyyoga.inc, PID: 4168
                                                  java.lang.NullPointerException: println needs a message
                                                      at android.util.Log.println_native(Native Method)
                                                      at android.util.Log.d(Log.java:158)
                                                      at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:308)
                                                      at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:171)
                                                      at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:218)
                                                      at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:22)
                                                      at com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage(QosReporter.java:79)
                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                      at android.os.Looper.loop(Looper.java:136)
                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
03-30 16:51:19.660 891-1292/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!

**Comment by tanhx2008** [comment]
升级最新版本

**Comment by huxugang** [comment]
compile 'com.qiniu:happy-dns:0.2.+'
    compile 'com.qiniu.pili:pili-android-qos:0.8.16'
    compile files('libs/PayPalAndroidSDK-2.9.11.jar'
请问下这些都是最新的吗，我现在用的是这个

**Comment by Jhuster** [comment]
@huxugang 升级到我们的 1.5.1 版本
