### ISSUE TITLE
关于底层编译so的问题

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#518]
我在Ubuntu上成功编译了so.但是加到项目中,报错了,我用的是1.5.0版本的.错误日志是:
java.lang.UnsatisfiedLinkError: No implementation found for long tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(int, long) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong__IJ)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.getSourcFpsVideo(IjkMediaPlayer.java:816)
	at com.pili.pldroid.player.PLMediaPlayer.f(PLMediaPlayer.java:1231)
	at com.pili.pldroid.player.PLMediaPlayer.A(PLMediaPlayer.java:78)
	at com.pili.pldroid.player.PLMediaPlayer$a.handleMessage(PLMediaPlayer.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yanxiandroid** [comment]
@Jhuster 现象是视频播放了,有声音,有画面,so文件应该是没问题的,但是马上就报错了错误日志如上,,因为我需要支持RMVB,mkv,avi格式,,希望您能给予我帮助和指导,谢谢!!

**Comment by zpscott** [comment]
我也刚遇到这问题 有解决么？我视频不播放。
