### ISSUE TITLE
Crash issue: IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by wjjiang917** [pili-engineering/PLDroidPlayer#530]
详细日志：
java.lang.IllegalArgumentException: Receiver not registered: com.pili.pldroid.player.report.core.d$2@ef22a4f
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:864)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1355)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
	at com.pili.pldroid.player.report.core.d.b(QosReceiver.java:80)
	at com.pili.pldroid.player.report.b.a(QosEnv.java:28)
	at com.pili.pldroid.player.report.core.f.b(QosStatusRecorder.java:324)
	at com.pili.pldroid.player.report.core.d.a(QosReceiver.java:110)
	at com.pili.pldroid.player.report.core.d.a(QosReceiver.java:14)
	at com.pili.pldroid.player.report.core.d$1.onReceive(QosReceiver.java:38)
	at com.pili.pldroid.player.report.a.c(QosBroadcastManager.java:299)
	at com.pili.pldroid.player.report.a.a(QosBroadcastManager.java:47)
	at com.pili.pldroid.player.report.a$1.handleMessage(QosBroadcastManager.java:87)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)

手机型号：
android 6.0 (23)，HUAWEI:HUAWEI VNS-L21:arm64-v8a

**Comment by Jhuster** [comment]
@wjjiang917 最新版本吗

**Comment by wjjiang917** [comment]
@Jhuster 是的。1.5.1的版本

**Comment by tanhx2008** [comment]
下一版本修复

**Comment by wjjiang917** [comment]
@tanhx2008  能否告知一下下个版本计划？大概什么时候发布 😁   ，谢谢🙏

**Comment by wjjiang917** [comment]
停止维护了吗？
