### ISSUE TITLE
java.lang.ClassCastException 出现了一个通信方式的类型转换错误

### ISSUE THREAD

**Issue by hlmichael** [pili-engineering/PLDroidPlayer#543]
java.lang.ClassCastException: android.telephony.CellInfoCdma cannot be cast to android.telephony.CellInfoLte
	at com.pili.pldroid.player.report.common.a.i(Util.java:814)
	at com.pili.pldroid.player.report.core.f.i(QosStatusRecorder.java:89)
	at com.pili.pldroid.player.report.core.f.j(QosStatusRecorder.java:111)
	at com.pili.pldroid.player.report.core.f.d(QosStatusRecorder.java:67)
	at com.pili.pldroid.player.report.core.d$2$1.run(QosReceiver.java:52)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
	at java.lang.Thread.run(Thread.java:818)
出现了一个通信方式的类型转换错误，不知道有方法解决吗

**Comment by Jhuster** [comment]
@hlmichael 请使用最新版本，已经修复
