### ISSUE TITLE
使用PLVideoViewActivity播放视频总是闪退

### ISSUE THREAD

**Issue by OwenDota** [pili-engineering/PLDroidPlayer#567]
java.lang.NoSuchMethodError: No virtual method getSourcFpsVideo()J in class Ltv/danmaku/ijk/media/player/IjkMediaPlayer; or its super classes (declaration of 'tv.danmaku.ijk.media.player.IjkMediaPlayer' appears in /data/app/com.suncoamba.goaction-1/base.apk:classes9.dex)
	at com.pili.pldroid.player.PLMediaPlayer.f(PLMediaPlayer.java:1235)
	at com.pili.pldroid.player.PLMediaPlayer.A(PLMediaPlayer.java:78)
	at com.pili.pldroid.player.PLMediaPlayer$a.handleMessage(PLMediaPlayer.java:1325)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jhuster** [comment]
@OwenDota app 是否加了 multidex

**Comment by OwenDota** [comment]
是的
![image](https://cloud.githubusercontent.com/assets/28776153/26436336/51f724ca-4148-11e7-838f-7856c7ee82f7.png)

**Comment by Jhuster** [comment]
@OwenDota 什么版本，确定同时更新了 jar 包和 so 文件吗

**Comment by OwenDota** [comment]
@Jhuster jar包是1.5.1，so包是releases包下的

**Comment by tanhx2008** [comment]
用我们 demo 是否正常？

**Comment by OwenDota** [comment]
用demo是正常的

**Comment by tanhx2008** [comment]
之前是否正常

**Comment by OwenDota** [comment]
我是今天才用的，之前没有用过

**Comment by OwenDota** [comment]
好了，我刚才的操作是将jar包和so包全部删除后，再重新导入jar包先运行后再导入so包就可以了
