### ISSUE TITLE
PLVideoTextureView1.5.1 进入播放界面，直接锁屏，程序闪退！！！

### ISSUE THREAD

**Issue by xiangchalong** [pili-engineering/PLDroidPlayer#570]
Log日志：
java.lang.RuntimeException: Unable to stop activity {com.dailyyoga.cn/com.dailyyoga.cn.activity.PLVideoTextureActivity}: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                                                                   at android.app.ActivityThread.handleSleeping(ActivityThread.java:3997)
                                                                   at android.app.ActivityThread.-wrap23(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6114)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                                Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                                                                   at java.util.ArrayList.get(ArrayList.java:411)
                                                                   at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:603)
                                                                   at android.app.Activity.performStop(Activity.java:6914)
                                                                   at android.app.ActivityThread.handleSleeping(ActivityThread.java:3994)
                                                                   at android.app.ActivityThread.-wrap23(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6114) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by xiangchalong** [comment]
用你们的Demo和集成到我的程序都是一样的结果，必现，请帮忙尽快定位，着急。

**Comment by Vander-liu** [comment]
@xiangchalong  解决了么 我也遇到一个问题 锁屏后的 Activity被关闭.,

**Comment by xiangchalong** [comment]
没有...

**Comment by HappyGhostz** [comment]
解决了吗  同样的.IndexOutOfBoundsException
