### ISSUE TITLE
PLVideoTextureView 在Sony Z2手机上无法播放直播视频

### ISSUE THREAD

**Issue by KevinSgun** [pili-engineering/PLDroidPlayer#573]
使用官方Demo播放也是一样无法播放，查看日志报错：
com.pili.pldroid.playerdemo W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
com.pili.pldroid.playerdemo W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

05-31 19:23:46.429 9810-19982/com.pili.pldroid.playerdemo E/IJKMEDIA: Cannot read RTMP handshake response
05-31 19:23:46.429 9810-19982/com.pili.pldroid.playerdemo E/IJKMEDIA: rtmp://157.255.155.189/testmaixiang/592ea089a95be75a00323a98?key=d652febd45dcc231&domain=pili-publish.testmaixiang.godochina.com: Immediate exit requested

但是我用其他手机却可以观看

**Comment by Jhuster** [comment]
@KevinSgun `pili-publish.testmaixiang.godochina.com` 是推流域名，请改为播放域名再试试

**Comment by Jhuster** [comment]
@KevinSgun `pili-publish.testmaixiang.godochina.com` 是推流域名，请改为播放域名再试试

**Comment by KevinSgun** [comment]
06-01 09:47:55.779 2642-6097/com.pili.pldroid.playerdemo E/IJKMEDIA: prepare timeout !
06-01 09:47:55.779 2642-6097/com.pili.pldroid.playerdemo E/IJKMEDIA: Cannot read RTMP handshake response
06-01 09:47:55.789 2642-6097/com.pili.pldroid.playerdemo E/IJKMEDIA: rtmp://157.255.155.190/testmaixiang/592f6fb8a3d5ec2fa4365f99?key=3bec01b4fd155f25&domain=pili-live-rtmp.testmaixiang.godochina.com: Immediate exit requested
06-01 09:47:55.789 2642-6097/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6097]
06-01 09:47:55.789 2642-6095/com.pili.pldroid.playerdemo D/IJKMEDIA: FFP_MSG_ERROR: -2001
06-01 09:47:55.789 2642-2642/com.pili.pldroid.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2001)
06-01 09:47:55.789 2642-2642/com.pili.pldroid.playerdemo E/PLMediaPlayer: Error happened, what = -10000, errorCode = -2001
06-01 09:47:55.789 2642-2642/com.pili.pldroid.playerdemo E/PLMediaPlayerActivity: Error happened, errorCode = -2001


换了之后还是和之前的一样，其他的手机可以播放，就这个Sony  Z2手机不行

**Comment by KevinSgun** [comment]
另外点播没有问题

**Comment by KevinSgun** [comment]
还是Sony Z2手机，在播放界面切换出去再回来就Crash了，报错如下:06-01 11:00:44.324 354-27625/com.godo.maixiang E/Looper: Error adding epoll events for fd -9, errno=9
06-01 11:00:44.534 354-27625/com.godo.maixiang E/AndroidRuntime: FATAL EXCEPTION: QosBroadcastManager
                                                                 Process: com.godo.maixiang, PID: 354
                                                                 java.lang.RuntimeException: Failed to initialize display event receiver.  status=-2147483648
                                                                     at android.view.DisplayEventReceiver.nativeInit(Native Method)
                                                                     at android.view.DisplayEventReceiver.<init>(DisplayEventReceiver.java:61)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.<init>(Choreographer.java:695)
                                                                     at android.view.Choreographer.<init>(Choreographer.java:169)
                                                                     at android.view.Choreographer.<init>(Choreographer.java:72)
                                                                     at android.view.Choreographer$1.initialValue(Choreographer.java:98)
                                                                     at android.view.Choreographer$1.initialValue(Choreographer.java:91)
                                                                     at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
                                                                     at java.lang.ThreadLocal.get(ThreadLocal.java:65)
                                                                     at android.view.Choreographer.getInstance(Choreographer.java:194)
                                                                     at com.pili.pldroid.player.report.common.a.g(Util.java:907)
                                                                     at com.pili.pldroid.player.report.core.d.a(QosReceiver.java:101)
                                                                     at com.pili.pldroid.player.report.core.d.a(QosReceiver.java:14)
                                                                     at com.pili.pldroid.player.report.core.d$1.onReceive(QosReceiver.java:38)
                                                                     at com.pili.pldroid.player.report.a.c(QosBroadcastManager.java:299)
                                                                     at com.pili.pldroid.player.report.a.a(QosBroadcastManager.java:47)
                                                                     at com.pili.pldroid.player.report.a$1.handleMessage(QosBroadcastManager.java:87)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:212)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by KevinSgun** [comment]
这个是日志文件
[log.txt](https://github.com/pili-engineering/PLDroidPlayer/files/1043555/log.txt)
