### ISSUE TITLE
PLVideoView 提示为Null

### ISSUE THREAD

**Issue by OaixGnauh** [pili-engineering/PLDroidPlayer#606]
XML布局：
        <com.pili.pldroid.player.widget.PLVideoView
            android:name="@+id/video_x"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center" />

代码：
PLVideoTextureView  mVideoView = (PLVideoTextureView) findViewById(R.id.video_x);

MediaController mMediaController = new MediaController(this);
mVideoView.setMediaController(mMediaController);  <- 该处抛出mVideoView为Null

布局异常提示：
java.lang.VerifyError: Expecting a stackmap frame at branch target 22
Exception Details:
  Location:
    com/pili/pldroid/player/widget/a.start()V @5: if_icmpne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 0094 08a0 0011 2a2a b401 1bb6 011f
    0x0000010: 2a06 b500 96b1 2ab7 015c 9900 0f2a b400
    0x0000020: d5b6 01c4 2a06 b500 942a 06b5 0096 b1  

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:404)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:262)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:220)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by x024** [comment]
1.6.0 第一次遇见findViewById后还提示null - - ，调试半天了。还是没找到原因只好来issues

**Comment by x024** [comment]
刚代码帖错了，应该为:
PLVideoView mVideoView = (PLVideoView) findViewById(R.id.video_x);
