### ISSUE TITLE
在4.x的手机版本经常报这个错误

### ISSUE THREAD

**Issue by SmallStoneDD** [pili-engineering/PLDroidPlayer#624]
java.lang.NoClassDefFoundError: com.pili.pldroid.player.PLMediaPlayer$3
	at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:743)
	at com.pili.pldroid.player.widget.a.c(PLBaseVideoView.java:490)
	at com.pili.pldroid.player.widget.a.setVideoURI(PLBaseVideoView.java:338)
	at com.pili.pldroid.player.widget.PLVideoView.setVideoURI(PLVideoView.java:20)
	at com.pili.pldroid.player.widget.a.setVideoPath(PLBaseVideoView.java:322)
	at com.pili.pldroid.player.widget.PLVideoView.setVideoPath(PLVideoView.java:20)
	at com.bjyx.dayup.ui.widget.StonePlayer.Play(StonePlayer.java:407)
	at com.bjyx.dayup.ui.widget.StonePlayer.access$1000(StonePlayer.java:55)
	at com.bjyx.dayup.ui.widget.StonePlayer$8.onSuccess(StonePlayer.java:364)
	at com.bjyx.dayup.ui.widget.StonePlayer$8.onSuccess(StonePlayer.java:351)
	at com.bjyx.mynetwork.core.AppActionImpl$25.onPostExecute(AppActionImpl.java:644)
	at com.bjyx.mynetwork.core.AppActionImpl$25.onPostExecute(AppActionImpl.java:636)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5178)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Jhuster** [comment]
@SmallStoneDD 有试过 demo 吗

**Comment by SmallStoneDD** [comment]
你好，找到错误原因了，是由于app方法数过多导致在5.0以下机型部分类库没有加载

**Comment by qp910** [comment]
@SmallStoneDD 你好，方法数过多导致库没加载，怎么修改的？

**Comment by SmallStoneDD** [comment]
@qp910 http://www.cnblogs.com/raomengyang/p/5863339.html
