### ISSUE TITLE
java.lang.NoSuchMethodError: no static method with name='postEventFromNative' signature='(Ljava/lang/Object;IIILjava/lang/Object;)V' in class Lcom/qiniu/qplayer/mediaEngine/MediaPlayer;

### ISSUE THREAD

**Issue by jinxiaojing** [pili-engineering/PLDroidPlayer#759]
at com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeInit(Native Method)
                                                       at com.qiniu.qplayer.mediaEngine.MediaPlayer.a(MediaPlayer.java:778)
                                                       at com.qiniu.qplayer.mediaEngine.MediaPlayer.<init>(MediaPlayer.java:110)
                                                       at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:101)
                                                       at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:97)
                                                       at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:547)
                                                       at com.pili.pldroid.player.widget.a$2.a(PLBaseVideoView.java:1063)
                                                       at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureAvailable(PLVideoTextureView.java:372)
                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:377)
                                                       at android.view.View.getDisplayList(View.java:13506)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.getDisplayList(View.java:13536)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.draw(View.java:14606)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                       at android.view.View.getDisplayList(View.java:13538)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.getDisplayList(View.java:13536)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.draw(View.java:14606)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                       at android.view.View.getDisplayList(View.java:13538)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.getDisplayList(View.java:13536)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.getDisplayList(View.java:13536)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.getDisplayList(View.java:13536)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.View.draw(View.java:14316)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
                                                       at android.view.View.draw(View.java:14606)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
                                                       at android.view.View.getDisplayList(View.java:13538)
                                                       at android.view.View.getDisplayList(View.java:13582)
                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2508)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2372)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2175)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5164)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
                                                   	at android.view.Cho

**Comment by jinxiaojing** [comment]
android4.2版本出现的错误

**Comment by jinxiaojing** [comment]
手机型号 三星GT_I9082C

**Comment by jinxiaojing** [comment]
2.0.0yi上版本

**Comment by HugoLipeng** [comment]
已沟通确认，是在x86下的老so没删除导致。
