### ISSUE TITLE
直播网络支持问题？

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#802]

**Comment by panyingdaoz** [comment]
在Android4.2.2版本中4G网络下运行会报这样的错误，并且闪退01-06 16:17:04.940 2861-2861/com.android.settings A/Environment: Static storage paths aren't available from AID_SYSTEM
                                                                 java.lang.Throwable
                                                                     at android.os.Environment.throwIfSystem(Environment.java:637)
                                                                     at android.os.Environment.getExternalStorageDirectory(Environment.java:316)
                                                                     at com.android.settings.DeviceInfoSettings.getSDCardMemory(DeviceInfoSettings.java:217)
                                                                     at com.android.settings.DeviceInfoSettings.onCreate(DeviceInfoSettings.java:112)
                                                                     at android.app.Fragment.performCreate(Fragment.java:1673)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:854)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:682)
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
                                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
                                                                     at android.os.Handler.handleCallback(Handler.java:725)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                     at dalvik.system.NativeStart.main(Native Method)
