### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed x86 error emulator android 6.xx  version 1.21

### ISSUE THREAD

**Issue by msdos2** [pili-engineering/PLDroidPlayer#82]
Process: com.pili.pldroid.playerdemo, PID: 1961
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.pili.pldroid.playerdemo-1/lib/x86/libpldroidplayer.so: has text relocations
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at com.pili.pldroid.player.SharedLibraryNameHelper.a(SharedLibraryNameHelper.java:36)
at com.pili.pldroid.player.PLMediaPlayer$1.loadLibrary(PLMediaPlayer.java:93)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:154)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:198)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:194)
at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:87)
at com.pili.pldroid.player.widget.a.b(PLBaseVideoView.java:264)
at com.pili.pldroid.player.widget.a$8.a(PLBaseVideoView.java:683)
at com.pili.pldroid.player.widget.PLVideoView$a$1.surfaceCreated(PLVideoView.java:94)
at android.view.SurfaceView.updateWindow(SurfaceView.java:582)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by longbai** [comment]
收到，我们看下

**Comment by Jhuster** [comment]
@msdos2 请问你是在哪一款手机上测试的？

**Comment by sunxu3074** [comment]
@Jhuster 一样的错误。Nexus 5 and Nexus 5x (os 6.0) (on simulator) 。
还有个问题，请教一下，为什么拖动seekbar有时候会拖不过去，一个半小时的资源，拖到半小时后时间就会显示复数，然后跳回前边。

**Comment by Jhuster** [comment]
@sunxu3074 本 issue 问题的解决办法建议参考：http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations

后面的问题，建议另起一个 issue
