### ISSUE TITLE
使用2.0.6出現java.lang.NoSuchMethodError: no static or non-static method "Lcom/qiniu/qplayer/mediaEngine/MediaPlayer;.nativeGetPos(J)J"

### ISSUE THREAD

**Issue by bb989** [pili-engineering/PLDroidPlayer#825]
Android Studio Generate Signed APK之後，運行到mMediaPlayer = new PLMediaPlayer(this, mAVOptions);會閃退並收到log如下，未Signed的測試版本卻可正常運行，請問是那裡有問題?
01-22 14:36:33.127 31546-31546/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.realma.realmatvcht02, PID: 31546
                                                   java.lang.NoSuchMethodError: no static or non-static method "Lcom/qiniu/qplayer/mediaEngine/MediaPlayer;.nativeGetPos(J)J"
                                                       at java.lang.Runtime.nativeLoad(Native Method)
                                                       at java.lang.Runtime.doLoad(Runtime.java:1060)
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:975)
                                                       at java.lang.System.loadLibrary(System.java:1567)
                                                       at com.qiniu.qplayer.mediaEngine.MediaPlayer.<clinit>(Unknown Source)
                                                       at com.b.a.a.b.a(Unknown Source)
                                                       at com.b.a.a.b.<init>(Unknown Source)
                                                       at com.realma.realmatvcht02.MediaPlayerActivity.c(Unknown Source)
                                                       at com.realma.realmatvcht02.MediaPlayerActivity.a(Unknown Source)
                                                       at com.realma.realmatvcht02.MediaPlayerActivity$1.surfaceCreated(Unknown Source)
                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:656)
                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2542)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by zshbleaker** [comment]
请在 proguard 配制中增加：

-keep class com.pili.pldroid.player.** { *; }
-keep class com.qiniu.qplayer.mediaEngine.MediaPlayer{*;}
