### ISSUE TITLE
按照sdk文档无法播放

### ISSUE THREAD

**Issue by FrankLove** [pili-engineering/PLDroidPlayer#829]
按照sdk的配置播放报这个错误，不知道是什么原因
``: FATAL EXCEPTION: main
                                                                           Process: com.conference.pldemotest, PID: 10658
                                                                           java.lang.NullPointerException
                                                                               at com.qiniu.qplayer.mediaEngine.MediaPlayer.getNetworkName(MediaPlayer.java:1028)
                                                                               at com.qiniu.qplayer.mediaEngine.MediaPlayer.init(MediaPlayer.java:793)
                                                                               at com.qiniu.qplayer.mediaEngine.MediaPlayer.<init>(MediaPlayer.java:113)
                                                                               at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:101)
                                                                               at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:97)
                                                                               at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:544)
                                                                               at com.pili.pldroid.player.widget.a$2.a(PLBaseVideoView.java:1059)
                                                                               at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureAvailable(PLVideoTextureView.java:372)
                                                                               at android.view.TextureView.getHardwareLayer(TextureView.java:396)

**Comment by zshbleaker** [comment]
请问使用的是哪个版本呢？2.0.6 应该修复了这个问题

**Comment by FrankLove** [comment]
@zshbleaker 最新的2.0.6

**Comment by zshbleaker** [comment]
请问有给 ACCESS_WIFI_STATE 权限吗？

**Comment by FrankLove** [comment]
@zshbleaker 没加，sdk文档上面只有这几个
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
加了后就没报这个错误了

**Comment by zshbleaker** [comment]
文档里忘记添加了，SDK 需要此权限来获取网络状态。这边给 SDK 新增了相关保护，感谢反馈
