### ISSUE TITLE
recylerview中使用PLVideoTextureView  滑动滑动崩溃

### ISSUE THREAD

**Issue by ymcao** [pili-engineering/PLDroidPlayer#842]
java.lang.IllegalArgumentException: Trying to setSurfaceTexture to the same SurfaceTexture that's already set.
                                                                            at android.view.TextureView.setSurfaceTexture(TextureView.java:795)
                                                                            at com.pili.pldroid.player.widget.PLVideoTextureView.a(PLVideoTextureView.java:245)
                                                                            at com.pili.pldroid.player.widget.a$2.a(PLBaseVideoView.java:1063)
                                                                            at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureAvailable(PLVideoTextureView.java:372)
                                                                            at android.view.TextureView.getHardwareLayer(TextureView.java:445)
                                                                            at android.view.TextureView.draw(TextureView.java:394)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16264)
                                                                            at android.view.View.draw(View.java:17048)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3784)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3570)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16259)
                                                                            at android.view.View.draw(View.java:17048)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3784)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3570)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16259)
                                                                            at android.view.View.draw(View.java:17048)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3784)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3570)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16259)
                                                                            at android.view.View.draw(View.java:17048)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3784)
                                                                            at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4461)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3570)
                                                                            at android.view.View.draw(View.java:17285)
                                                                            at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3853)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16264)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3768)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3748)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16227)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:3141)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2924)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1443)
02-01 22:14:27.732 13475-13475/com.youzu.livesdk.demo E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6918)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:690)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:625)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:185)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6493)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
                                                                            at co

**Comment by zshbleaker** [comment]
这个问题在新版本中已经修复，预计下周初更新，感谢反馈
