### ISSUE TITLE
new PLMediaPlayer NullPointerException 2.0.6

### ISSUE THREAD

**Issue by benntqoo** [pili-engineering/PLDroidPlayer#847]
`  mAVOptions = new AVOptions();
   mAVOptions.setInteger(AVOptions.KEY_PREPARE_TIMEOUT, 10 * 1000);
   mAVOptions.setInteger(AVOptions.KEY_MEDIACODEC, 0);
   mAVOptions.setInteger(AVOptions.KEY_LIVE_STREAMING,  0);
   mAVOptions.setInteger(AVOptions.KEY_LOG_LEVEL, 0);
   mMediaPlayer = new PLMediaPlayer(mContext, mAVOptions);

02-06 00:41:36.552 12372-12372/com.impublishinggroup.readerapp I/QPlayer: init: 2.0.5, QPlayer-v1.1.0.58, 16842810
02-06 00:41:36.552 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC CNDKPlayer L55 The device propertity is 5.1.1
02-06 00:41:36.552 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC CNDKPlayer L77 Post event method = 0x74136028
02-06 00:41:36.552 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC COMBoxMng L74 SDK version 1.1.0.58, 17:54:20 Dec 22 2017
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000100 start.
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc =        0. Used Time: 0
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000101 start.
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc = -2147483640. Used Time: 0
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000004 start.
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc =        0. Used Time: 0
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetNotifyFunc Value is 00000000 start.
02-06 00:41:36.554 12372-12372/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L278 ----SetNotifyFunc leave! no return. Ussed Time: 0
02-06 00:41:36.562 12372-12372/com.impublishinggroup.readerapp D/AndroidRuntime: Shutting down VM
02-06 00:41:36.609 12372-12372/com.impublishinggroup.readerapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.impublishinggroup.readerapp, PID: 12372
                                                                                 java.lang.NullPointerException: Attempt to read from null array
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.getNetworkName(MediaPlayer.java:1028)
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.init(MediaPlayer.java:793)
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.<init>(MediaPlayer.java:113)
                                                                                     at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:101)
                                                                                     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:97)
                                                                                     at com.impublishinggroup.readerapp.helpers.PLAudioPlayerHelper.prepare(PLAudioPlayerHelper.java:195)
`

**Comment by zshbleaker** [comment]
2.0.6 修复了这个问题，可以更新版本试试

**Comment by benntqoo** [comment]
我就是用 2.0.6
一開始可以的
測試也沒問題
上架之後就繃了...

**Comment by zshbleaker** [comment]
你的 log 里写的是 2.0.5 呀

**Comment by benntqoo** [comment]
@zshbleaker 

抱歉 一開始是用 2.0.6 剛剛想說降板試試看

02-06 01:34:37.518 29710-29710/com.impublishinggroup.readerapp I/QPlayer: init: 2.0.6, QPlayer-v1.1.0.58, 16842810
02-06 01:34:37.518 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC CNDKPlayer L55 The device propertity is 5.1.1
02-06 01:34:37.518 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC CNDKPlayer L77 Post event method = 0x74136430
02-06 01:34:37.518 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC COMBoxMng L74 SDK version 1.1.0.58, 17:54:20 Dec 22 2017
02-06 01:34:37.519 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000100 start.
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc =        0. Used Time: 0
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000101 start.
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc = -2147483640. Used Time: 0
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetParam Value is 11000004 start.
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L274 ----SetParam leave! rc =        0. Used Time: 0
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L256 ----SetNotifyFunc Value is 00000000 start.
02-06 01:34:37.520 29710-29710/com.impublishinggroup.readerapp I/@@@QCLOG: Info TB6F14BEC QCFuncLog L278 ----SetNotifyFunc leave! no return. Ussed Time: 0
02-06 01:34:37.528 29710-29710/com.impublishinggroup.readerapp D/AndroidRuntime: Shutting down VM
02-06 01:34:37.534 29710-29710/com.impublishinggroup.readerapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.impublishinggroup.readerapp, PID: 29710
                                                                                 java.lang.NullPointerException: Attempt to read from null array
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.getNetworkName(MediaPlayer.java:1028)
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.init(MediaPlayer.java:793)
                                                                                     at com.qiniu.qplayer.mediaEngine.MediaPlayer.<init>(MediaPlayer.java:113)
                                                                                     at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:101)
                                                                                     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:97)
                                                                                     at com.impublishinggroup.readerapp.helpers.PLAudioPlayerHelper.prepare(PLAudioPlayerHelper.java:195)
                                                                                     at com.impublishinggroup.readerapp.helpers.PLAudioPlayerHelper.<init>(PLAudioPlayerHelper.java:140)
                                                                                     at com.impublishinggroup.readerapp.helpers.PLAudioPlayerHelper.newInstance(PLAudioPlayerHelper.java:118)
                                                                                     at com.impublishinggroup.readerapp.fragments.mainActivity.qrCode.RadioFragment.onResume(RadioFragment.java:173)
                                                                                     at android.support.v4.app.Fragment.performResume(Fragment.java:2308)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                                     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                                     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:211)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
02-06 01:34:47.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 COMBoxMng L1373 The Event ID = 70000004
02-06 01:34:47.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 QCFuncLog L256 ----OnHandleEvent Value is 70000004 start.
02-06 01:34:47.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 QCFuncLog L274 ----OnHandleEvent leave! rc =        0. Used Time: 0
02-06 01:34:57.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 COMBoxMng L1373 The Event ID = 70000004
02-06 01:34:57.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 QCFuncLog L256 ----OnHandleEvent Value is 70000004 start.
02-06 01:34:57.519 29710-30371/com.impublishinggroup.readerapp I/@@@QCLOG: Info TAF1C8000 QCFuncLog L274 ----OnHandleEvent leave! rc =        0. Used Time: 0

**Comment by zshbleaker** [comment]
好的，我明天看一下，记得之前修过这个问题

**Comment by benntqoo** [comment]
需要堤共 gradle 配置嗎?

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.impublishinggroup.readerapp"
        minSdkVersion 18
        targetSdkVersion 27
        versionCode 15
        versionName "1.2.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            resValue("string", "PORT_NUMBER", "8081")//database debug port
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //android components
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    //other
    //    implementation 'joda-time:joda-time:2.9.4'
    //fire base
//    compile 'com.google.firebase:firebase-core:11.8.0'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.google.firebase:firebase-storage:11.8.0'
    implementation 'com.google.firebase:firebase-auth:11.8.0'
    implementation 'com.google.firebase:firebase-config:11.8.0'
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    //rx pattern
    compile 'io.reactivex.rxjava2:rxjava:2.1.7'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    //rx bind
    compile 'com.jakewharton.rxbinding2:rxbinding:2.1.0'
    //rxPermission
    compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar'
    //squareup
    //    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    //    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    //    compile 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    //    compile 'com.squareup.okhttp3:okhttp:3.9.1'
    //butter knife
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    // green dao
    compile 'org.greenrobot:greendao:3.2.2'
    compile 'net.zetetic:android-database-sqlcipher:3.5.7@aar'
    //glide4.3.1
    compile 'com.github.bumptech.glide:glide:4.4.0'
    // zxing
    compile 'com.google.zxing:core:3.3.0'
    compile 'com.journeyapps:zxing-android-embedded:3.5.0'
    //tree view
    compile 'com.github.bmelnychuk:atv:1.2.+'
    //Database Debug
    //    debugCompile 'com.amitshekhar.android:debug-db:1.0.1'
    //FB SDK
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    //country code pick
    compile 'com.hbb20:ccp:2.1.2'
    // Enabling multidex support.
    compile 'com.android.support:multidex:1.0.1'
    compile files('libs/pldroid-player-2.0.6.jar')
}
apply plugin: 'com.google.gms.google-services'

**Comment by benntqoo** [comment]
我解決問題了

看一下源碼
MediaPlayer.class 837 行的 這方法有錯
  private String getNetworkName() {
        String var1 = Util.netType(this.mAppContext);
        return !var1.equals("Unknown") && !var1.equals("None") && !var1.isEmpty()?(Util.netType(this.mAppContext).equals("WIFI")?Util.getWifiInfo(this.mAppContext)[0]:Util.getPhoneInfo(this.mAppContext)[0]):null;
    }

後來是在 manifest 上補權限
 <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
補上 wifi 狀態權限就可以正常使用了
比較不理解的是
一開始開發自己封裝、測試 都正常
上架後卻崩了 ...
