### ISSUE TITLE
Permission denied (missing INTERNET permission?) 在manifest已经配置了网络权限，但是在某些机型上还是会报错

### ISSUE THREAD

**Issue by yuanting2016** [pili-engineering/PLDroidPlayer#870]
Fatal Exception: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:221)
       at com.pili.pldroid.report.core.c.a(QosReporter.java:146)
       at com.pili.pldroid.report.core.c.a(QosReporter.java:93)
       at com.pili.pldroid.report.core.c.a(QosReporter.java:16)
       at com.pili.pldroid.report.core.c$1.handleMessage(QosReporter.java:39)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by zshbleaker** [comment]
请问用的什么版本？这个类不是播放器里的

**Comment by HugoLipeng** [comment]
推流里面早先的版本用到了qos,目前不需要这个引用，升级推流的版本即可
