### ISSUE TITLE
播放音频视频时偶先崩溃

### ISSUE THREAD

**Issue by xushichao08** [pili-engineering/PLDroidPlayer#886]
你好，使用贵公司的sdk，在音频时拖动seekbar到最后，或者重新设置音频源prepareAsync后，偶尔会崩溃。机型为华为荣耀6
报错信息
Caught a RuntimeException from the binder stub implementation.
                                         java.lang.NullPointerException
                                             at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
                                             at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
                                             at android.os.Binder.execTransact(Binder.java:404)
                                             at dalvik.system.NativeStart.run(Native Method)

**Comment by zshbleaker** [comment]
请问这个问题只在华为荣耀 6 上出现吗？以及任何音频流都会出现吗？

**Comment by xushichao08** [comment]
是的，只有在华为荣耀6上出现，快速打开关闭视频也会出现这种崩溃。
