### ISSUE TITLE
2.1.2RecyclerView中播放视频快速滑动内存回收不及时造成卡死

### ISSUE THREAD

**Issue by pengfeigao** [pili-engineering/PLDroidPlayer#901]
2.1.1版本无此问题。

**Comment by chenxiruanhai** [comment]
我也遇到了这个问题,日志如下
`E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'release' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:184)
at android.view.Surface.setNativeObjectLocked(Surface.java:471)
at android.view.Surface.<init>(Surface.java:146)
at com.pili.pldroid.player.widget.PLVideoTextureView$PLTextureRenderView$1.onSurfaceTextureDestroyed(PLVideoTextureView.java:360)
at android.view.TextureView.destroySurface(TextureView.java:237)
at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:227)
at android.view.View.dispatchDetachedFromWindow(View.java:13624)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2864)
at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4556)
at android.view.ViewGroup.removeAllViews(ViewGroup.java:4502)`
