### ISSUE TITLE
PLMediaPlayer.getVideoWidth()' on a null object reference

### ISSUE THREAD

**Issue by xieguangqing** [pili-engineering/PLDroidPlayer#944]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.pili.pldroid.player.PLMediaPlayer.getVideoWidth()' on a null object reference
    at com.pili.pldroid.player.widget.a$4.onVideoSizeChanged(SourceFile:789)
    at com.qiniu.qplayer.mediaEngine.MediaPlayer$10.run(SourceFile:1288)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:181)
    at android.app.ActivityThread.main(ActivityThread.java:6294)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by ReikyZ** [comment]
这个在目前最新版（2.1.4）应该已经修复，升级看下
