### ISSUE TITLE
项目引用renderscript高斯模糊处理图片播放器不能正常注册，无法播放视频

### ISSUE THREAD

**Issue by haohe1990** [pili-engineering/PLDroidPlayer#975]
W/System.err: java.lang.UnsatisfiedLinkError: com.qiniu.qplayer.mediaEngine.MediaPlayer
  W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:47)
  W/System.err:     at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:570)
  W/System.err:     at com.pili.pldroid.player.widget.a$3.a(PLBaseVideoView.java:1138)
  W/System.err:     at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureAvailable(PLVideoTextureView.java:346)
  W/System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:368)
  W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15261)
  W/System.err:     at android.view.View.draw(View.java:16072)
  W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
  W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
  W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15279)
  W/System.err:     at android.view.View.draw(View.java:16072)
  W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
  W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
  W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15279)
  W/System.err:     at android.view.View.draw(View.java:16072)
  W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
  W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
  W/System.err:     at android.view.View.draw(View.java:16305)

**Comment by haohe1990** [comment]
//        renderscriptTargetApi = 19
//        renderscriptSupportModeEnabled = true

这个是gradle引用
